apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zcp-registry
    component: mysql
    release: zcp-registry
  name: mysql-data-zcp-registry-harbor-mysql-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: managed-standard-retain
